name: Web

on:
  workflow_dispatch:
  push:
    branches: [main, stable]
    paths:
      - .github/workflows/web.yml
      - web/**

  pull_request:
    branches: [main, stable]
    paths:
      - .github/workflows/web.yml
      - web/**

  schedule:
    - cron: 0 1 * * 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: web/yarn.lock

      - name: Lint
        run: yarn lint
        working-directory: web

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: web/yarn.lock

      - name: Test
        run: yarn test
        working-directory: web
