name: Website

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/website.yml
      - website/**
      - docs/**
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed, reopened]

# TODO: rename secrets DEPLOY_SSH_KEY to PREVIEW_DEPLOY_KEY
env:
  PREVIEW_EXTERNAL_REPOSITORY: jooola/libretime-preview
  PREVIEW_URL: https://jooola.github.io
  PREVIEW_BASE_URL: /libretime-preview

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vale
        run: |
          sudo pip3 install gh-release-install
          sudo gh-release-install \
            errata-ai/vale \
            vale_{version}_Linux_64-bit.tar.gz --extract vale \
            /usr/local/bin/vale

      - name: Add annotations matchers
        run: |
          echo "::add-matcher::.github/annotations/vale.json"

      - name: Run Vale
        run: |
          make -C .github/vale/styles
          vale --output line docs website/src/pages || true

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy
    runs-on: ubuntu-latest
    needs: [lint]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: ./website/yarn.lock

      - name: Install
        working-directory: website
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: website
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build

  preview:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    name: Preview
    runs-on: ubuntu-latest
    needs: [lint]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: ./website/yarn.lock

      - name: Install
        working-directory: website
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: website
        run: yarn build
        env:
          URL: ${{ env.PREVIEW_URL }}
          BASE_URL: ${{ env.PREVIEW_BASE_URL }}/pr-${{ github.event.pull_request.number }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: ${{ env.PREVIEW_EXTERNAL_REPOSITORY }}
          deploy_key: ${{ secrets.DEPLOY_SSH_KEY }}
          publish_dir: website/build
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true

      - name: Send PR preview link
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Deployment preview
            😎 Preview this PR: ${{ env.PREVIEW_URL }}${{ env.PREVIEW_BASE_URL }}/pr-${{ github.event.pull_request.number }}/
            🧑🏼‍💻 Commit SHA: ${{ github.sha }}

  clean-preview:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Clean preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.PREVIEW_EXTERNAL_REPOSITORY }}
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Clean files
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          rm -fR pr-${{ github.event.pull_request.number }}

          git add .
          git commit -m "Clean pr-${{ github.event.pull_request.number }} review"
          git push
