name: Website

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/website.yml
      - website/**
      - docs/**
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: ./website/yarn.lock

      - name: Install
        working-directory: website
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: website
        run: yarn build

      - uses: actions/upload-artifact@v3
        with:
          name: website-${{ github.sha }}
          path: website/build
          retention-days: 1

  # deploy:
  #   if: github.ref == 'refs/heads/main'
  #   name: Deploy
  #   runs-on: ubuntu-latest

  #   needs: [build]

  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: website-${{ github.sha }}
  #         path: website/build

  #     - name: Deploy
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: website/build
